/*
 * Nodeum API
 *
 * # About  This document describes the Nodeum API version 2:  If you are looking for any information about the product itself, reach the product website https://www.nodeum.io. You can also contact us at this email address : info@nodeum.io  # Filter parameters When browsing a list of items, multiple filter parameters may be applied. Some operators can be added to the value as a prefix:  - `=` value is equal. Default operator, may be omitted  - `!=` value is different  - `>` greater than  - `>=` greater than or equal  - `<` lower than  - `>=` lower than or equal  - `><` included in list, items should be separated by `|`  - `!><` not included in list, items should be separated by `|`  - `~` pattern matching, may include `%` (any characters) and `_` (one character)  - `!~` pattern not matching, may include `%` (any characters) and `_` (one character)  
 *
 * API version: 2.1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package nodeum

import (
	"context"
	"io/ioutil"
	"net/http"
	"net/url"
	"strings"
	"fmt"
	"github.com/antihax/optional"
)

// Linger please
var (
	_ context.Context
)

type TapeDrivesApiService service

/* 
TapeDrivesApiService Creates a new tape drive.
**API Key Scope**: tape_drives / create
 * @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 * @param tapeLibraryId Numeric ID, serial, or name of tape library.
 * @param tapeDriveBody

@return TapeDrive
*/
func (a *TapeDrivesApiService) CreateTapeDriveByTapeLibrary(ctx context.Context, tapeLibraryId string, tapeDriveBody TapeDrive) (TapeDrive, *http.Response, error) {
	var (
		localVarHttpMethod = strings.ToUpper("Post")
		localVarPostBody   interface{}
		localVarFileName   string
		localVarFileBytes  []byte
		localVarReturnValue TapeDrive
	)

	// create path and map variables
	localVarPath := a.client.cfg.BasePath + "/tape_libraries/{tape_library_id}/tape_drives"
	localVarPath = strings.Replace(localVarPath, "{"+"tape_library_id"+"}", fmt.Sprintf("%v", tapeLibraryId), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHttpContentTypes := []string{"application/json"}

	// set Content-Type header
	localVarHttpContentType := selectHeaderContentType(localVarHttpContentTypes)
	if localVarHttpContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHttpContentType
	}

	// to determine the Accept header
	localVarHttpHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHttpHeaderAccept := selectHeaderAccept(localVarHttpHeaderAccepts)
	if localVarHttpHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHttpHeaderAccept
	}
	// body params
	localVarPostBody = &tapeDriveBody
	if ctx != nil {
		// API Key Authentication
		if auth, ok := ctx.Value(ContextAPIKey).(APIKey); ok {
			var key string
			if auth.Prefix != "" {
				key = auth.Prefix + " " + auth.Key
			} else {
				key = auth.Key
			}
			localVarHeaderParams["Authorization"] = key
			
		}
	}
	r, err := a.client.prepareRequest(ctx, localVarPath, localVarHttpMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, localVarFileName, localVarFileBytes)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHttpResponse, err := a.client.callAPI(r)
	if err != nil || localVarHttpResponse == nil {
		return localVarReturnValue, localVarHttpResponse, err
	}

	localVarBody, err := ioutil.ReadAll(localVarHttpResponse.Body)
	localVarHttpResponse.Body.Close()
	if err != nil {
		return localVarReturnValue, localVarHttpResponse, err
	}

	if localVarHttpResponse.StatusCode < 300 {
		// If we succeed, return the data, otherwise pass on to decode error.
		err = a.client.decode(&localVarReturnValue, localVarBody, localVarHttpResponse.Header.Get("Content-Type"));
		if err == nil { 
			return localVarReturnValue, localVarHttpResponse, err
		}
	}

	if localVarHttpResponse.StatusCode >= 300 {
		newErr := GenericSwaggerError{
			body: localVarBody,
			error: localVarHttpResponse.Status,
		}
		
		if localVarHttpResponse.StatusCode == 201 {
			var v TapeDrive
			err = a.client.decode(&v, localVarBody, localVarHttpResponse.Header.Get("Content-Type"));
				if err != nil {
					newErr.error = err.Error()
					return localVarReturnValue, localVarHttpResponse, newErr
				}
				newErr.model = v
				return localVarReturnValue, localVarHttpResponse, newErr
		}
		
		if localVarHttpResponse.StatusCode == 422 {
			var v ModelError
			err = a.client.decode(&v, localVarBody, localVarHttpResponse.Header.Get("Content-Type"));
				if err != nil {
					newErr.error = err.Error()
					return localVarReturnValue, localVarHttpResponse, newErr
				}
				newErr.model = v
				return localVarReturnValue, localVarHttpResponse, newErr
		}
		
		return localVarReturnValue, localVarHttpResponse, newErr
	}

	return localVarReturnValue, localVarHttpResponse, nil
}

/* 
TapeDrivesApiService Destroys a specific tape drive.
**API Key Scope**: tape_drives / destroy
 * @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 * @param tapeDriveId Numeric ID, serial, or name of tape drive.


*/
func (a *TapeDrivesApiService) DestroyTapeDrive(ctx context.Context, tapeDriveId string) (*http.Response, error) {
	var (
		localVarHttpMethod = strings.ToUpper("Delete")
		localVarPostBody   interface{}
		localVarFileName   string
		localVarFileBytes  []byte
		
	)

	// create path and map variables
	localVarPath := a.client.cfg.BasePath + "/tape_drives/{tape_drive_id}"
	localVarPath = strings.Replace(localVarPath, "{"+"tape_drive_id"+"}", fmt.Sprintf("%v", tapeDriveId), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHttpContentTypes := []string{"application/json"}

	// set Content-Type header
	localVarHttpContentType := selectHeaderContentType(localVarHttpContentTypes)
	if localVarHttpContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHttpContentType
	}

	// to determine the Accept header
	localVarHttpHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHttpHeaderAccept := selectHeaderAccept(localVarHttpHeaderAccepts)
	if localVarHttpHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHttpHeaderAccept
	}
	if ctx != nil {
		// API Key Authentication
		if auth, ok := ctx.Value(ContextAPIKey).(APIKey); ok {
			var key string
			if auth.Prefix != "" {
				key = auth.Prefix + " " + auth.Key
			} else {
				key = auth.Key
			}
			localVarHeaderParams["Authorization"] = key
			
		}
	}
	r, err := a.client.prepareRequest(ctx, localVarPath, localVarHttpMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, localVarFileName, localVarFileBytes)
	if err != nil {
		return nil, err
	}

	localVarHttpResponse, err := a.client.callAPI(r)
	if err != nil || localVarHttpResponse == nil {
		return localVarHttpResponse, err
	}

	localVarBody, err := ioutil.ReadAll(localVarHttpResponse.Body)
	localVarHttpResponse.Body.Close()
	if err != nil {
		return localVarHttpResponse, err
	}


	if localVarHttpResponse.StatusCode >= 300 {
		newErr := GenericSwaggerError{
			body: localVarBody,
			error: localVarHttpResponse.Status,
		}
		
		return localVarHttpResponse, newErr
	}

	return localVarHttpResponse, nil
}

/* 
TapeDrivesApiService Destroys a specific tape drive.
**API Key Scope**: tape_drives / destroy
 * @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 * @param tapeLibraryId Numeric ID, serial, or name of tape library.
 * @param tapeDriveId Numeric ID, serial, or name of tape drive.


*/
func (a *TapeDrivesApiService) DestroyTapeDriveByTapeLibrary(ctx context.Context, tapeLibraryId string, tapeDriveId string) (*http.Response, error) {
	var (
		localVarHttpMethod = strings.ToUpper("Delete")
		localVarPostBody   interface{}
		localVarFileName   string
		localVarFileBytes  []byte
		
	)

	// create path and map variables
	localVarPath := a.client.cfg.BasePath + "/tape_libraries/{tape_library_id}/tape_drives/{tape_drive_id}"
	localVarPath = strings.Replace(localVarPath, "{"+"tape_library_id"+"}", fmt.Sprintf("%v", tapeLibraryId), -1)
	localVarPath = strings.Replace(localVarPath, "{"+"tape_drive_id"+"}", fmt.Sprintf("%v", tapeDriveId), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHttpContentTypes := []string{"application/json"}

	// set Content-Type header
	localVarHttpContentType := selectHeaderContentType(localVarHttpContentTypes)
	if localVarHttpContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHttpContentType
	}

	// to determine the Accept header
	localVarHttpHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHttpHeaderAccept := selectHeaderAccept(localVarHttpHeaderAccepts)
	if localVarHttpHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHttpHeaderAccept
	}
	if ctx != nil {
		// API Key Authentication
		if auth, ok := ctx.Value(ContextAPIKey).(APIKey); ok {
			var key string
			if auth.Prefix != "" {
				key = auth.Prefix + " " + auth.Key
			} else {
				key = auth.Key
			}
			localVarHeaderParams["Authorization"] = key
			
		}
	}
	r, err := a.client.prepareRequest(ctx, localVarPath, localVarHttpMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, localVarFileName, localVarFileBytes)
	if err != nil {
		return nil, err
	}

	localVarHttpResponse, err := a.client.callAPI(r)
	if err != nil || localVarHttpResponse == nil {
		return localVarHttpResponse, err
	}

	localVarBody, err := ioutil.ReadAll(localVarHttpResponse.Body)
	localVarHttpResponse.Body.Close()
	if err != nil {
		return localVarHttpResponse, err
	}


	if localVarHttpResponse.StatusCode >= 300 {
		newErr := GenericSwaggerError{
			body: localVarBody,
			error: localVarHttpResponse.Status,
		}
		
		return localVarHttpResponse, newErr
	}

	return localVarHttpResponse, nil
}

/* 
TapeDrivesApiService Lists tape drives devices.
**API Key Scope**: tape_drives / devices
 * @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 * @param tapeLibraryId Numeric ID, serial, or name of tape library.
 * @param optional nil or *IndexTapeDriveDevicesOpts - Optional Parameters:
     * @param "JobId" (optional.String) -  ID of active job

@return TapeDriveDeviceCollection
*/

type IndexTapeDriveDevicesOpts struct { 
	JobId optional.String
}

func (a *TapeDrivesApiService) IndexTapeDriveDevices(ctx context.Context, tapeLibraryId string, localVarOptionals *IndexTapeDriveDevicesOpts) (TapeDriveDeviceCollection, *http.Response, error) {
	var (
		localVarHttpMethod = strings.ToUpper("Get")
		localVarPostBody   interface{}
		localVarFileName   string
		localVarFileBytes  []byte
		localVarReturnValue TapeDriveDeviceCollection
	)

	// create path and map variables
	localVarPath := a.client.cfg.BasePath + "/tape_libraries/{tape_library_id}/tape_drives/-/devices"
	localVarPath = strings.Replace(localVarPath, "{"+"tape_library_id"+"}", fmt.Sprintf("%v", tapeLibraryId), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	if localVarOptionals != nil && localVarOptionals.JobId.IsSet() {
		localVarQueryParams.Add("job_id", parameterToString(localVarOptionals.JobId.Value(), ""))
	}
	// to determine the Content-Type header
	localVarHttpContentTypes := []string{"application/json"}

	// set Content-Type header
	localVarHttpContentType := selectHeaderContentType(localVarHttpContentTypes)
	if localVarHttpContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHttpContentType
	}

	// to determine the Accept header
	localVarHttpHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHttpHeaderAccept := selectHeaderAccept(localVarHttpHeaderAccepts)
	if localVarHttpHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHttpHeaderAccept
	}
	if ctx != nil {
		// API Key Authentication
		if auth, ok := ctx.Value(ContextAPIKey).(APIKey); ok {
			var key string
			if auth.Prefix != "" {
				key = auth.Prefix + " " + auth.Key
			} else {
				key = auth.Key
			}
			localVarHeaderParams["Authorization"] = key
			
		}
	}
	r, err := a.client.prepareRequest(ctx, localVarPath, localVarHttpMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, localVarFileName, localVarFileBytes)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHttpResponse, err := a.client.callAPI(r)
	if err != nil || localVarHttpResponse == nil {
		return localVarReturnValue, localVarHttpResponse, err
	}

	localVarBody, err := ioutil.ReadAll(localVarHttpResponse.Body)
	localVarHttpResponse.Body.Close()
	if err != nil {
		return localVarReturnValue, localVarHttpResponse, err
	}

	if localVarHttpResponse.StatusCode < 300 {
		// If we succeed, return the data, otherwise pass on to decode error.
		err = a.client.decode(&localVarReturnValue, localVarBody, localVarHttpResponse.Header.Get("Content-Type"));
		if err == nil { 
			return localVarReturnValue, localVarHttpResponse, err
		}
	}

	if localVarHttpResponse.StatusCode >= 300 {
		newErr := GenericSwaggerError{
			body: localVarBody,
			error: localVarHttpResponse.Status,
		}
		
		if localVarHttpResponse.StatusCode == 200 {
			var v TapeDriveDeviceCollection
			err = a.client.decode(&v, localVarBody, localVarHttpResponse.Header.Get("Content-Type"));
				if err != nil {
					newErr.error = err.Error()
					return localVarReturnValue, localVarHttpResponse, newErr
				}
				newErr.model = v
				return localVarReturnValue, localVarHttpResponse, newErr
		}
		
		if localVarHttpResponse.StatusCode == 202 {
			var v ActiveJobStatus
			err = a.client.decode(&v, localVarBody, localVarHttpResponse.Header.Get("Content-Type"));
				if err != nil {
					newErr.error = err.Error()
					return localVarReturnValue, localVarHttpResponse, newErr
				}
				newErr.model = v
				return localVarReturnValue, localVarHttpResponse, newErr
		}
		
		if localVarHttpResponse.StatusCode == 500 {
			var v ActiveJobStatus
			err = a.client.decode(&v, localVarBody, localVarHttpResponse.Header.Get("Content-Type"));
				if err != nil {
					newErr.error = err.Error()
					return localVarReturnValue, localVarHttpResponse, newErr
				}
				newErr.model = v
				return localVarReturnValue, localVarHttpResponse, newErr
		}
		
		return localVarReturnValue, localVarHttpResponse, newErr
	}

	return localVarReturnValue, localVarHttpResponse, nil
}

/* 
TapeDrivesApiService Lists all tape drives.
**API Key Scope**: tape_drives / index
 * @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 * @param optional nil or *IndexTapeDrivesOpts - Optional Parameters:
     * @param "Limit" (optional.Int32) -  The number of items to display for pagination.
     * @param "Offset" (optional.Int32) -  The number of items to skip for pagination.
     * @param "SortBy" (optional.Interface of []string) -  Sort results by attribute.  Can sort on multiple attributes, separated by &#x60;|&#x60;. Order direction can be suffixing the attribute by either &#x60;:asc&#x60; (default) or &#x60;:desc&#x60;.
     * @param "Id" (optional.String) -  Filter on id
     * @param "TapeLibraryId" (optional.String) -  Filter on tape library id
     * @param "Name" (optional.String) -  Filter on name
     * @param "Serial" (optional.String) -  Filter on serial
     * @param "Comment" (optional.String) -  Filter on comment
     * @param "ScsiAddress" (optional.String) -  Filter on scsi address
     * @param "Vendor" (optional.String) -  Filter on vendor
     * @param "Product" (optional.String) -  Filter on product
     * @param "Firmware" (optional.String) -  Filter on firmware
     * @param "Device" (optional.String) -  Filter on device
     * @param "Sgdevice" (optional.String) -  Filter on sgdevice
     * @param "Libso" (optional.String) -  Filter on libso
     * @param "Acs" (optional.String) -  Filter on acs
     * @param "Lsm" (optional.String) -  Filter on lsm
     * @param "Panel" (optional.String) -  Filter on panel
     * @param "Transport" (optional.String) -  Filter on transport
     * @param "Status" (optional.String) -  Filter on status
     * @param "Full" (optional.String) -  Filter on full
     * @param "MountCount" (optional.String) -  Filter on mount count
     * @param "UseTo" (optional.String) -  Filter on use to
     * @param "UseBy" (optional.String) -  Filter on use by
     * @param "Barcode" (optional.String) -  Filter on barcode
     * @param "TaskId" (optional.String) -  Filter on task id
     * @param "UseFileProcessedSize" (optional.String) -  Filter on use file processed size
     * @param "UseFileSizeToProcess" (optional.String) -  Filter on use file size to process
     * @param "UseFileNameProcessed" (optional.String) -  Filter on use file name processed
     * @param "Bandwidth" (optional.String) -  Filter on bandwidth

@return TapeDriveCollection
*/

type IndexTapeDrivesOpts struct { 
	Limit optional.Int32
	Offset optional.Int32
	SortBy optional.Interface
	Id optional.String
	TapeLibraryId optional.String
	Name optional.String
	Serial optional.String
	Comment optional.String
	ScsiAddress optional.String
	Vendor optional.String
	Product optional.String
	Firmware optional.String
	Device optional.String
	Sgdevice optional.String
	Libso optional.String
	Acs optional.String
	Lsm optional.String
	Panel optional.String
	Transport optional.String
	Status optional.String
	Full optional.String
	MountCount optional.String
	UseTo optional.String
	UseBy optional.String
	Barcode optional.String
	TaskId optional.String
	UseFileProcessedSize optional.String
	UseFileSizeToProcess optional.String
	UseFileNameProcessed optional.String
	Bandwidth optional.String
}

func (a *TapeDrivesApiService) IndexTapeDrives(ctx context.Context, localVarOptionals *IndexTapeDrivesOpts) (TapeDriveCollection, *http.Response, error) {
	var (
		localVarHttpMethod = strings.ToUpper("Get")
		localVarPostBody   interface{}
		localVarFileName   string
		localVarFileBytes  []byte
		localVarReturnValue TapeDriveCollection
	)

	// create path and map variables
	localVarPath := a.client.cfg.BasePath + "/tape_drives"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	if localVarOptionals != nil && localVarOptionals.Limit.IsSet() {
		localVarQueryParams.Add("limit", parameterToString(localVarOptionals.Limit.Value(), ""))
	}
	if localVarOptionals != nil && localVarOptionals.Offset.IsSet() {
		localVarQueryParams.Add("offset", parameterToString(localVarOptionals.Offset.Value(), ""))
	}
	if localVarOptionals != nil && localVarOptionals.SortBy.IsSet() {
		localVarQueryParams.Add("sort_by", parameterToString(localVarOptionals.SortBy.Value(), "pipes"))
	}
	if localVarOptionals != nil && localVarOptionals.Id.IsSet() {
		localVarQueryParams.Add("id", parameterToString(localVarOptionals.Id.Value(), ""))
	}
	if localVarOptionals != nil && localVarOptionals.TapeLibraryId.IsSet() {
		localVarQueryParams.Add("tape_library_id", parameterToString(localVarOptionals.TapeLibraryId.Value(), ""))
	}
	if localVarOptionals != nil && localVarOptionals.Name.IsSet() {
		localVarQueryParams.Add("name", parameterToString(localVarOptionals.Name.Value(), ""))
	}
	if localVarOptionals != nil && localVarOptionals.Serial.IsSet() {
		localVarQueryParams.Add("serial", parameterToString(localVarOptionals.Serial.Value(), ""))
	}
	if localVarOptionals != nil && localVarOptionals.Comment.IsSet() {
		localVarQueryParams.Add("comment", parameterToString(localVarOptionals.Comment.Value(), ""))
	}
	if localVarOptionals != nil && localVarOptionals.ScsiAddress.IsSet() {
		localVarQueryParams.Add("scsi_address", parameterToString(localVarOptionals.ScsiAddress.Value(), ""))
	}
	if localVarOptionals != nil && localVarOptionals.Vendor.IsSet() {
		localVarQueryParams.Add("vendor", parameterToString(localVarOptionals.Vendor.Value(), ""))
	}
	if localVarOptionals != nil && localVarOptionals.Product.IsSet() {
		localVarQueryParams.Add("product", parameterToString(localVarOptionals.Product.Value(), ""))
	}
	if localVarOptionals != nil && localVarOptionals.Firmware.IsSet() {
		localVarQueryParams.Add("firmware", parameterToString(localVarOptionals.Firmware.Value(), ""))
	}
	if localVarOptionals != nil && localVarOptionals.Device.IsSet() {
		localVarQueryParams.Add("device", parameterToString(localVarOptionals.Device.Value(), ""))
	}
	if localVarOptionals != nil && localVarOptionals.Sgdevice.IsSet() {
		localVarQueryParams.Add("sgdevice", parameterToString(localVarOptionals.Sgdevice.Value(), ""))
	}
	if localVarOptionals != nil && localVarOptionals.Libso.IsSet() {
		localVarQueryParams.Add("libso", parameterToString(localVarOptionals.Libso.Value(), ""))
	}
	if localVarOptionals != nil && localVarOptionals.Acs.IsSet() {
		localVarQueryParams.Add("acs", parameterToString(localVarOptionals.Acs.Value(), ""))
	}
	if localVarOptionals != nil && localVarOptionals.Lsm.IsSet() {
		localVarQueryParams.Add("lsm", parameterToString(localVarOptionals.Lsm.Value(), ""))
	}
	if localVarOptionals != nil && localVarOptionals.Panel.IsSet() {
		localVarQueryParams.Add("panel", parameterToString(localVarOptionals.Panel.Value(), ""))
	}
	if localVarOptionals != nil && localVarOptionals.Transport.IsSet() {
		localVarQueryParams.Add("transport", parameterToString(localVarOptionals.Transport.Value(), ""))
	}
	if localVarOptionals != nil && localVarOptionals.Status.IsSet() {
		localVarQueryParams.Add("status", parameterToString(localVarOptionals.Status.Value(), ""))
	}
	if localVarOptionals != nil && localVarOptionals.Full.IsSet() {
		localVarQueryParams.Add("full", parameterToString(localVarOptionals.Full.Value(), ""))
	}
	if localVarOptionals != nil && localVarOptionals.MountCount.IsSet() {
		localVarQueryParams.Add("mount_count", parameterToString(localVarOptionals.MountCount.Value(), ""))
	}
	if localVarOptionals != nil && localVarOptionals.UseTo.IsSet() {
		localVarQueryParams.Add("use_to", parameterToString(localVarOptionals.UseTo.Value(), ""))
	}
	if localVarOptionals != nil && localVarOptionals.UseBy.IsSet() {
		localVarQueryParams.Add("use_by", parameterToString(localVarOptionals.UseBy.Value(), ""))
	}
	if localVarOptionals != nil && localVarOptionals.Barcode.IsSet() {
		localVarQueryParams.Add("barcode", parameterToString(localVarOptionals.Barcode.Value(), ""))
	}
	if localVarOptionals != nil && localVarOptionals.TaskId.IsSet() {
		localVarQueryParams.Add("task_id", parameterToString(localVarOptionals.TaskId.Value(), ""))
	}
	if localVarOptionals != nil && localVarOptionals.UseFileProcessedSize.IsSet() {
		localVarQueryParams.Add("use_file_processed_size", parameterToString(localVarOptionals.UseFileProcessedSize.Value(), ""))
	}
	if localVarOptionals != nil && localVarOptionals.UseFileSizeToProcess.IsSet() {
		localVarQueryParams.Add("use_file_size_to_process", parameterToString(localVarOptionals.UseFileSizeToProcess.Value(), ""))
	}
	if localVarOptionals != nil && localVarOptionals.UseFileNameProcessed.IsSet() {
		localVarQueryParams.Add("use_file_name_processed", parameterToString(localVarOptionals.UseFileNameProcessed.Value(), ""))
	}
	if localVarOptionals != nil && localVarOptionals.Bandwidth.IsSet() {
		localVarQueryParams.Add("bandwidth", parameterToString(localVarOptionals.Bandwidth.Value(), ""))
	}
	// to determine the Content-Type header
	localVarHttpContentTypes := []string{"application/json"}

	// set Content-Type header
	localVarHttpContentType := selectHeaderContentType(localVarHttpContentTypes)
	if localVarHttpContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHttpContentType
	}

	// to determine the Accept header
	localVarHttpHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHttpHeaderAccept := selectHeaderAccept(localVarHttpHeaderAccepts)
	if localVarHttpHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHttpHeaderAccept
	}
	if ctx != nil {
		// API Key Authentication
		if auth, ok := ctx.Value(ContextAPIKey).(APIKey); ok {
			var key string
			if auth.Prefix != "" {
				key = auth.Prefix + " " + auth.Key
			} else {
				key = auth.Key
			}
			localVarHeaderParams["Authorization"] = key
			
		}
	}
	r, err := a.client.prepareRequest(ctx, localVarPath, localVarHttpMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, localVarFileName, localVarFileBytes)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHttpResponse, err := a.client.callAPI(r)
	if err != nil || localVarHttpResponse == nil {
		return localVarReturnValue, localVarHttpResponse, err
	}

	localVarBody, err := ioutil.ReadAll(localVarHttpResponse.Body)
	localVarHttpResponse.Body.Close()
	if err != nil {
		return localVarReturnValue, localVarHttpResponse, err
	}

	if localVarHttpResponse.StatusCode < 300 {
		// If we succeed, return the data, otherwise pass on to decode error.
		err = a.client.decode(&localVarReturnValue, localVarBody, localVarHttpResponse.Header.Get("Content-Type"));
		if err == nil { 
			return localVarReturnValue, localVarHttpResponse, err
		}
	}

	if localVarHttpResponse.StatusCode >= 300 {
		newErr := GenericSwaggerError{
			body: localVarBody,
			error: localVarHttpResponse.Status,
		}
		
		if localVarHttpResponse.StatusCode == 200 {
			var v TapeDriveCollection
			err = a.client.decode(&v, localVarBody, localVarHttpResponse.Header.Get("Content-Type"));
				if err != nil {
					newErr.error = err.Error()
					return localVarReturnValue, localVarHttpResponse, newErr
				}
				newErr.model = v
				return localVarReturnValue, localVarHttpResponse, newErr
		}
		
		return localVarReturnValue, localVarHttpResponse, newErr
	}

	return localVarReturnValue, localVarHttpResponse, nil
}

/* 
TapeDrivesApiService Lists all tape drives.
**API Key Scope**: tape_drives / index
 * @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 * @param tapeLibraryId Numeric ID, serial, or name of tape library.
 * @param optional nil or *IndexTapeDrivesByTapeLibraryOpts - Optional Parameters:
     * @param "Limit" (optional.Int32) -  The number of items to display for pagination.
     * @param "Offset" (optional.Int32) -  The number of items to skip for pagination.
     * @param "SortBy" (optional.Interface of []string) -  Sort results by attribute.  Can sort on multiple attributes, separated by &#x60;|&#x60;. Order direction can be suffixing the attribute by either &#x60;:asc&#x60; (default) or &#x60;:desc&#x60;.
     * @param "Id" (optional.String) -  Filter on id
     * @param "Name" (optional.String) -  Filter on name
     * @param "Serial" (optional.String) -  Filter on serial
     * @param "Comment" (optional.String) -  Filter on comment
     * @param "ScsiAddress" (optional.String) -  Filter on scsi address
     * @param "Vendor" (optional.String) -  Filter on vendor
     * @param "Product" (optional.String) -  Filter on product
     * @param "Firmware" (optional.String) -  Filter on firmware
     * @param "Device" (optional.String) -  Filter on device
     * @param "Sgdevice" (optional.String) -  Filter on sgdevice
     * @param "Libso" (optional.String) -  Filter on libso
     * @param "Acs" (optional.String) -  Filter on acs
     * @param "Lsm" (optional.String) -  Filter on lsm
     * @param "Panel" (optional.String) -  Filter on panel
     * @param "Transport" (optional.String) -  Filter on transport
     * @param "Status" (optional.String) -  Filter on status
     * @param "Full" (optional.String) -  Filter on full
     * @param "MountCount" (optional.String) -  Filter on mount count
     * @param "UseTo" (optional.String) -  Filter on use to
     * @param "UseBy" (optional.String) -  Filter on use by
     * @param "Barcode" (optional.String) -  Filter on barcode
     * @param "TaskId" (optional.String) -  Filter on task id
     * @param "UseFileProcessedSize" (optional.String) -  Filter on use file processed size
     * @param "UseFileSizeToProcess" (optional.String) -  Filter on use file size to process
     * @param "UseFileNameProcessed" (optional.String) -  Filter on use file name processed
     * @param "Bandwidth" (optional.String) -  Filter on bandwidth

@return TapeDriveCollection
*/

type IndexTapeDrivesByTapeLibraryOpts struct { 
	Limit optional.Int32
	Offset optional.Int32
	SortBy optional.Interface
	Id optional.String
	Name optional.String
	Serial optional.String
	Comment optional.String
	ScsiAddress optional.String
	Vendor optional.String
	Product optional.String
	Firmware optional.String
	Device optional.String
	Sgdevice optional.String
	Libso optional.String
	Acs optional.String
	Lsm optional.String
	Panel optional.String
	Transport optional.String
	Status optional.String
	Full optional.String
	MountCount optional.String
	UseTo optional.String
	UseBy optional.String
	Barcode optional.String
	TaskId optional.String
	UseFileProcessedSize optional.String
	UseFileSizeToProcess optional.String
	UseFileNameProcessed optional.String
	Bandwidth optional.String
}

func (a *TapeDrivesApiService) IndexTapeDrivesByTapeLibrary(ctx context.Context, tapeLibraryId string, localVarOptionals *IndexTapeDrivesByTapeLibraryOpts) (TapeDriveCollection, *http.Response, error) {
	var (
		localVarHttpMethod = strings.ToUpper("Get")
		localVarPostBody   interface{}
		localVarFileName   string
		localVarFileBytes  []byte
		localVarReturnValue TapeDriveCollection
	)

	// create path and map variables
	localVarPath := a.client.cfg.BasePath + "/tape_libraries/{tape_library_id}/tape_drives"
	localVarPath = strings.Replace(localVarPath, "{"+"tape_library_id"+"}", fmt.Sprintf("%v", tapeLibraryId), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	if localVarOptionals != nil && localVarOptionals.Limit.IsSet() {
		localVarQueryParams.Add("limit", parameterToString(localVarOptionals.Limit.Value(), ""))
	}
	if localVarOptionals != nil && localVarOptionals.Offset.IsSet() {
		localVarQueryParams.Add("offset", parameterToString(localVarOptionals.Offset.Value(), ""))
	}
	if localVarOptionals != nil && localVarOptionals.SortBy.IsSet() {
		localVarQueryParams.Add("sort_by", parameterToString(localVarOptionals.SortBy.Value(), "pipes"))
	}
	if localVarOptionals != nil && localVarOptionals.Id.IsSet() {
		localVarQueryParams.Add("id", parameterToString(localVarOptionals.Id.Value(), ""))
	}
	if localVarOptionals != nil && localVarOptionals.Name.IsSet() {
		localVarQueryParams.Add("name", parameterToString(localVarOptionals.Name.Value(), ""))
	}
	if localVarOptionals != nil && localVarOptionals.Serial.IsSet() {
		localVarQueryParams.Add("serial", parameterToString(localVarOptionals.Serial.Value(), ""))
	}
	if localVarOptionals != nil && localVarOptionals.Comment.IsSet() {
		localVarQueryParams.Add("comment", parameterToString(localVarOptionals.Comment.Value(), ""))
	}
	if localVarOptionals != nil && localVarOptionals.ScsiAddress.IsSet() {
		localVarQueryParams.Add("scsi_address", parameterToString(localVarOptionals.ScsiAddress.Value(), ""))
	}
	if localVarOptionals != nil && localVarOptionals.Vendor.IsSet() {
		localVarQueryParams.Add("vendor", parameterToString(localVarOptionals.Vendor.Value(), ""))
	}
	if localVarOptionals != nil && localVarOptionals.Product.IsSet() {
		localVarQueryParams.Add("product", parameterToString(localVarOptionals.Product.Value(), ""))
	}
	if localVarOptionals != nil && localVarOptionals.Firmware.IsSet() {
		localVarQueryParams.Add("firmware", parameterToString(localVarOptionals.Firmware.Value(), ""))
	}
	if localVarOptionals != nil && localVarOptionals.Device.IsSet() {
		localVarQueryParams.Add("device", parameterToString(localVarOptionals.Device.Value(), ""))
	}
	if localVarOptionals != nil && localVarOptionals.Sgdevice.IsSet() {
		localVarQueryParams.Add("sgdevice", parameterToString(localVarOptionals.Sgdevice.Value(), ""))
	}
	if localVarOptionals != nil && localVarOptionals.Libso.IsSet() {
		localVarQueryParams.Add("libso", parameterToString(localVarOptionals.Libso.Value(), ""))
	}
	if localVarOptionals != nil && localVarOptionals.Acs.IsSet() {
		localVarQueryParams.Add("acs", parameterToString(localVarOptionals.Acs.Value(), ""))
	}
	if localVarOptionals != nil && localVarOptionals.Lsm.IsSet() {
		localVarQueryParams.Add("lsm", parameterToString(localVarOptionals.Lsm.Value(), ""))
	}
	if localVarOptionals != nil && localVarOptionals.Panel.IsSet() {
		localVarQueryParams.Add("panel", parameterToString(localVarOptionals.Panel.Value(), ""))
	}
	if localVarOptionals != nil && localVarOptionals.Transport.IsSet() {
		localVarQueryParams.Add("transport", parameterToString(localVarOptionals.Transport.Value(), ""))
	}
	if localVarOptionals != nil && localVarOptionals.Status.IsSet() {
		localVarQueryParams.Add("status", parameterToString(localVarOptionals.Status.Value(), ""))
	}
	if localVarOptionals != nil && localVarOptionals.Full.IsSet() {
		localVarQueryParams.Add("full", parameterToString(localVarOptionals.Full.Value(), ""))
	}
	if localVarOptionals != nil && localVarOptionals.MountCount.IsSet() {
		localVarQueryParams.Add("mount_count", parameterToString(localVarOptionals.MountCount.Value(), ""))
	}
	if localVarOptionals != nil && localVarOptionals.UseTo.IsSet() {
		localVarQueryParams.Add("use_to", parameterToString(localVarOptionals.UseTo.Value(), ""))
	}
	if localVarOptionals != nil && localVarOptionals.UseBy.IsSet() {
		localVarQueryParams.Add("use_by", parameterToString(localVarOptionals.UseBy.Value(), ""))
	}
	if localVarOptionals != nil && localVarOptionals.Barcode.IsSet() {
		localVarQueryParams.Add("barcode", parameterToString(localVarOptionals.Barcode.Value(), ""))
	}
	if localVarOptionals != nil && localVarOptionals.TaskId.IsSet() {
		localVarQueryParams.Add("task_id", parameterToString(localVarOptionals.TaskId.Value(), ""))
	}
	if localVarOptionals != nil && localVarOptionals.UseFileProcessedSize.IsSet() {
		localVarQueryParams.Add("use_file_processed_size", parameterToString(localVarOptionals.UseFileProcessedSize.Value(), ""))
	}
	if localVarOptionals != nil && localVarOptionals.UseFileSizeToProcess.IsSet() {
		localVarQueryParams.Add("use_file_size_to_process", parameterToString(localVarOptionals.UseFileSizeToProcess.Value(), ""))
	}
	if localVarOptionals != nil && localVarOptionals.UseFileNameProcessed.IsSet() {
		localVarQueryParams.Add("use_file_name_processed", parameterToString(localVarOptionals.UseFileNameProcessed.Value(), ""))
	}
	if localVarOptionals != nil && localVarOptionals.Bandwidth.IsSet() {
		localVarQueryParams.Add("bandwidth", parameterToString(localVarOptionals.Bandwidth.Value(), ""))
	}
	// to determine the Content-Type header
	localVarHttpContentTypes := []string{"application/json"}

	// set Content-Type header
	localVarHttpContentType := selectHeaderContentType(localVarHttpContentTypes)
	if localVarHttpContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHttpContentType
	}

	// to determine the Accept header
	localVarHttpHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHttpHeaderAccept := selectHeaderAccept(localVarHttpHeaderAccepts)
	if localVarHttpHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHttpHeaderAccept
	}
	if ctx != nil {
		// API Key Authentication
		if auth, ok := ctx.Value(ContextAPIKey).(APIKey); ok {
			var key string
			if auth.Prefix != "" {
				key = auth.Prefix + " " + auth.Key
			} else {
				key = auth.Key
			}
			localVarHeaderParams["Authorization"] = key
			
		}
	}
	r, err := a.client.prepareRequest(ctx, localVarPath, localVarHttpMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, localVarFileName, localVarFileBytes)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHttpResponse, err := a.client.callAPI(r)
	if err != nil || localVarHttpResponse == nil {
		return localVarReturnValue, localVarHttpResponse, err
	}

	localVarBody, err := ioutil.ReadAll(localVarHttpResponse.Body)
	localVarHttpResponse.Body.Close()
	if err != nil {
		return localVarReturnValue, localVarHttpResponse, err
	}

	if localVarHttpResponse.StatusCode < 300 {
		// If we succeed, return the data, otherwise pass on to decode error.
		err = a.client.decode(&localVarReturnValue, localVarBody, localVarHttpResponse.Header.Get("Content-Type"));
		if err == nil { 
			return localVarReturnValue, localVarHttpResponse, err
		}
	}

	if localVarHttpResponse.StatusCode >= 300 {
		newErr := GenericSwaggerError{
			body: localVarBody,
			error: localVarHttpResponse.Status,
		}
		
		if localVarHttpResponse.StatusCode == 200 {
			var v TapeDriveCollection
			err = a.client.decode(&v, localVarBody, localVarHttpResponse.Header.Get("Content-Type"));
				if err != nil {
					newErr.error = err.Error()
					return localVarReturnValue, localVarHttpResponse, newErr
				}
				newErr.model = v
				return localVarReturnValue, localVarHttpResponse, newErr
		}
		
		return localVarReturnValue, localVarHttpResponse, newErr
	}

	return localVarReturnValue, localVarHttpResponse, nil
}

/* 
TapeDrivesApiService Displays a specific tape drive.
**API Key Scope**: tape_drives / show
 * @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 * @param tapeDriveId Numeric ID, serial, or name of tape drive.

@return TapeDrive
*/
func (a *TapeDrivesApiService) ShowTapeDrive(ctx context.Context, tapeDriveId string) (TapeDrive, *http.Response, error) {
	var (
		localVarHttpMethod = strings.ToUpper("Get")
		localVarPostBody   interface{}
		localVarFileName   string
		localVarFileBytes  []byte
		localVarReturnValue TapeDrive
	)

	// create path and map variables
	localVarPath := a.client.cfg.BasePath + "/tape_drives/{tape_drive_id}"
	localVarPath = strings.Replace(localVarPath, "{"+"tape_drive_id"+"}", fmt.Sprintf("%v", tapeDriveId), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHttpContentTypes := []string{"application/json"}

	// set Content-Type header
	localVarHttpContentType := selectHeaderContentType(localVarHttpContentTypes)
	if localVarHttpContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHttpContentType
	}

	// to determine the Accept header
	localVarHttpHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHttpHeaderAccept := selectHeaderAccept(localVarHttpHeaderAccepts)
	if localVarHttpHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHttpHeaderAccept
	}
	if ctx != nil {
		// API Key Authentication
		if auth, ok := ctx.Value(ContextAPIKey).(APIKey); ok {
			var key string
			if auth.Prefix != "" {
				key = auth.Prefix + " " + auth.Key
			} else {
				key = auth.Key
			}
			localVarHeaderParams["Authorization"] = key
			
		}
	}
	r, err := a.client.prepareRequest(ctx, localVarPath, localVarHttpMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, localVarFileName, localVarFileBytes)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHttpResponse, err := a.client.callAPI(r)
	if err != nil || localVarHttpResponse == nil {
		return localVarReturnValue, localVarHttpResponse, err
	}

	localVarBody, err := ioutil.ReadAll(localVarHttpResponse.Body)
	localVarHttpResponse.Body.Close()
	if err != nil {
		return localVarReturnValue, localVarHttpResponse, err
	}

	if localVarHttpResponse.StatusCode < 300 {
		// If we succeed, return the data, otherwise pass on to decode error.
		err = a.client.decode(&localVarReturnValue, localVarBody, localVarHttpResponse.Header.Get("Content-Type"));
		if err == nil { 
			return localVarReturnValue, localVarHttpResponse, err
		}
	}

	if localVarHttpResponse.StatusCode >= 300 {
		newErr := GenericSwaggerError{
			body: localVarBody,
			error: localVarHttpResponse.Status,
		}
		
		if localVarHttpResponse.StatusCode == 200 {
			var v TapeDrive
			err = a.client.decode(&v, localVarBody, localVarHttpResponse.Header.Get("Content-Type"));
				if err != nil {
					newErr.error = err.Error()
					return localVarReturnValue, localVarHttpResponse, newErr
				}
				newErr.model = v
				return localVarReturnValue, localVarHttpResponse, newErr
		}
		
		return localVarReturnValue, localVarHttpResponse, newErr
	}

	return localVarReturnValue, localVarHttpResponse, nil
}

/* 
TapeDrivesApiService Displays a specific tape drive.
**API Key Scope**: tape_drives / show
 * @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 * @param tapeLibraryId Numeric ID, serial, or name of tape library.
 * @param tapeDriveId Numeric ID, serial, or name of tape drive.

@return TapeDrive
*/
func (a *TapeDrivesApiService) ShowTapeDriveByTapeLibrary(ctx context.Context, tapeLibraryId string, tapeDriveId string) (TapeDrive, *http.Response, error) {
	var (
		localVarHttpMethod = strings.ToUpper("Get")
		localVarPostBody   interface{}
		localVarFileName   string
		localVarFileBytes  []byte
		localVarReturnValue TapeDrive
	)

	// create path and map variables
	localVarPath := a.client.cfg.BasePath + "/tape_libraries/{tape_library_id}/tape_drives/{tape_drive_id}"
	localVarPath = strings.Replace(localVarPath, "{"+"tape_library_id"+"}", fmt.Sprintf("%v", tapeLibraryId), -1)
	localVarPath = strings.Replace(localVarPath, "{"+"tape_drive_id"+"}", fmt.Sprintf("%v", tapeDriveId), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHttpContentTypes := []string{"application/json"}

	// set Content-Type header
	localVarHttpContentType := selectHeaderContentType(localVarHttpContentTypes)
	if localVarHttpContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHttpContentType
	}

	// to determine the Accept header
	localVarHttpHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHttpHeaderAccept := selectHeaderAccept(localVarHttpHeaderAccepts)
	if localVarHttpHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHttpHeaderAccept
	}
	if ctx != nil {
		// API Key Authentication
		if auth, ok := ctx.Value(ContextAPIKey).(APIKey); ok {
			var key string
			if auth.Prefix != "" {
				key = auth.Prefix + " " + auth.Key
			} else {
				key = auth.Key
			}
			localVarHeaderParams["Authorization"] = key
			
		}
	}
	r, err := a.client.prepareRequest(ctx, localVarPath, localVarHttpMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, localVarFileName, localVarFileBytes)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHttpResponse, err := a.client.callAPI(r)
	if err != nil || localVarHttpResponse == nil {
		return localVarReturnValue, localVarHttpResponse, err
	}

	localVarBody, err := ioutil.ReadAll(localVarHttpResponse.Body)
	localVarHttpResponse.Body.Close()
	if err != nil {
		return localVarReturnValue, localVarHttpResponse, err
	}

	if localVarHttpResponse.StatusCode < 300 {
		// If we succeed, return the data, otherwise pass on to decode error.
		err = a.client.decode(&localVarReturnValue, localVarBody, localVarHttpResponse.Header.Get("Content-Type"));
		if err == nil { 
			return localVarReturnValue, localVarHttpResponse, err
		}
	}

	if localVarHttpResponse.StatusCode >= 300 {
		newErr := GenericSwaggerError{
			body: localVarBody,
			error: localVarHttpResponse.Status,
		}
		
		if localVarHttpResponse.StatusCode == 200 {
			var v TapeDrive
			err = a.client.decode(&v, localVarBody, localVarHttpResponse.Header.Get("Content-Type"));
				if err != nil {
					newErr.error = err.Error()
					return localVarReturnValue, localVarHttpResponse, newErr
				}
				newErr.model = v
				return localVarReturnValue, localVarHttpResponse, newErr
		}
		
		return localVarReturnValue, localVarHttpResponse, newErr
	}

	return localVarReturnValue, localVarHttpResponse, nil
}

/* 
TapeDrivesApiService Updates a specific tape drive.
**API Key Scope**: tape_drives / update
 * @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 * @param tapeDriveId Numeric ID, serial, or name of tape drive.
 * @param tapeDriveBody

@return TapeDrive
*/
func (a *TapeDrivesApiService) UpdateTapeDrive(ctx context.Context, tapeDriveId string, tapeDriveBody TapeDrive) (TapeDrive, *http.Response, error) {
	var (
		localVarHttpMethod = strings.ToUpper("Put")
		localVarPostBody   interface{}
		localVarFileName   string
		localVarFileBytes  []byte
		localVarReturnValue TapeDrive
	)

	// create path and map variables
	localVarPath := a.client.cfg.BasePath + "/tape_drives/{tape_drive_id}"
	localVarPath = strings.Replace(localVarPath, "{"+"tape_drive_id"+"}", fmt.Sprintf("%v", tapeDriveId), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHttpContentTypes := []string{"application/json"}

	// set Content-Type header
	localVarHttpContentType := selectHeaderContentType(localVarHttpContentTypes)
	if localVarHttpContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHttpContentType
	}

	// to determine the Accept header
	localVarHttpHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHttpHeaderAccept := selectHeaderAccept(localVarHttpHeaderAccepts)
	if localVarHttpHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHttpHeaderAccept
	}
	// body params
	localVarPostBody = &tapeDriveBody
	if ctx != nil {
		// API Key Authentication
		if auth, ok := ctx.Value(ContextAPIKey).(APIKey); ok {
			var key string
			if auth.Prefix != "" {
				key = auth.Prefix + " " + auth.Key
			} else {
				key = auth.Key
			}
			localVarHeaderParams["Authorization"] = key
			
		}
	}
	r, err := a.client.prepareRequest(ctx, localVarPath, localVarHttpMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, localVarFileName, localVarFileBytes)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHttpResponse, err := a.client.callAPI(r)
	if err != nil || localVarHttpResponse == nil {
		return localVarReturnValue, localVarHttpResponse, err
	}

	localVarBody, err := ioutil.ReadAll(localVarHttpResponse.Body)
	localVarHttpResponse.Body.Close()
	if err != nil {
		return localVarReturnValue, localVarHttpResponse, err
	}

	if localVarHttpResponse.StatusCode < 300 {
		// If we succeed, return the data, otherwise pass on to decode error.
		err = a.client.decode(&localVarReturnValue, localVarBody, localVarHttpResponse.Header.Get("Content-Type"));
		if err == nil { 
			return localVarReturnValue, localVarHttpResponse, err
		}
	}

	if localVarHttpResponse.StatusCode >= 300 {
		newErr := GenericSwaggerError{
			body: localVarBody,
			error: localVarHttpResponse.Status,
		}
		
		if localVarHttpResponse.StatusCode == 200 {
			var v TapeDrive
			err = a.client.decode(&v, localVarBody, localVarHttpResponse.Header.Get("Content-Type"));
				if err != nil {
					newErr.error = err.Error()
					return localVarReturnValue, localVarHttpResponse, newErr
				}
				newErr.model = v
				return localVarReturnValue, localVarHttpResponse, newErr
		}
		
		if localVarHttpResponse.StatusCode == 422 {
			var v ModelError
			err = a.client.decode(&v, localVarBody, localVarHttpResponse.Header.Get("Content-Type"));
				if err != nil {
					newErr.error = err.Error()
					return localVarReturnValue, localVarHttpResponse, newErr
				}
				newErr.model = v
				return localVarReturnValue, localVarHttpResponse, newErr
		}
		
		return localVarReturnValue, localVarHttpResponse, newErr
	}

	return localVarReturnValue, localVarHttpResponse, nil
}

/* 
TapeDrivesApiService Updates a specific tape drive.
**API Key Scope**: tape_drives / update
 * @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 * @param tapeLibraryId Numeric ID, serial, or name of tape library.
 * @param tapeDriveId Numeric ID, serial, or name of tape drive.
 * @param tapeDriveBody

@return TapeDrive
*/
func (a *TapeDrivesApiService) UpdateTapeDriveByTapeLibrary(ctx context.Context, tapeLibraryId string, tapeDriveId string, tapeDriveBody TapeDrive) (TapeDrive, *http.Response, error) {
	var (
		localVarHttpMethod = strings.ToUpper("Put")
		localVarPostBody   interface{}
		localVarFileName   string
		localVarFileBytes  []byte
		localVarReturnValue TapeDrive
	)

	// create path and map variables
	localVarPath := a.client.cfg.BasePath + "/tape_libraries/{tape_library_id}/tape_drives/{tape_drive_id}"
	localVarPath = strings.Replace(localVarPath, "{"+"tape_library_id"+"}", fmt.Sprintf("%v", tapeLibraryId), -1)
	localVarPath = strings.Replace(localVarPath, "{"+"tape_drive_id"+"}", fmt.Sprintf("%v", tapeDriveId), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHttpContentTypes := []string{"application/json"}

	// set Content-Type header
	localVarHttpContentType := selectHeaderContentType(localVarHttpContentTypes)
	if localVarHttpContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHttpContentType
	}

	// to determine the Accept header
	localVarHttpHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHttpHeaderAccept := selectHeaderAccept(localVarHttpHeaderAccepts)
	if localVarHttpHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHttpHeaderAccept
	}
	// body params
	localVarPostBody = &tapeDriveBody
	if ctx != nil {
		// API Key Authentication
		if auth, ok := ctx.Value(ContextAPIKey).(APIKey); ok {
			var key string
			if auth.Prefix != "" {
				key = auth.Prefix + " " + auth.Key
			} else {
				key = auth.Key
			}
			localVarHeaderParams["Authorization"] = key
			
		}
	}
	r, err := a.client.prepareRequest(ctx, localVarPath, localVarHttpMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, localVarFileName, localVarFileBytes)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHttpResponse, err := a.client.callAPI(r)
	if err != nil || localVarHttpResponse == nil {
		return localVarReturnValue, localVarHttpResponse, err
	}

	localVarBody, err := ioutil.ReadAll(localVarHttpResponse.Body)
	localVarHttpResponse.Body.Close()
	if err != nil {
		return localVarReturnValue, localVarHttpResponse, err
	}

	if localVarHttpResponse.StatusCode < 300 {
		// If we succeed, return the data, otherwise pass on to decode error.
		err = a.client.decode(&localVarReturnValue, localVarBody, localVarHttpResponse.Header.Get("Content-Type"));
		if err == nil { 
			return localVarReturnValue, localVarHttpResponse, err
		}
	}

	if localVarHttpResponse.StatusCode >= 300 {
		newErr := GenericSwaggerError{
			body: localVarBody,
			error: localVarHttpResponse.Status,
		}
		
		if localVarHttpResponse.StatusCode == 200 {
			var v TapeDrive
			err = a.client.decode(&v, localVarBody, localVarHttpResponse.Header.Get("Content-Type"));
				if err != nil {
					newErr.error = err.Error()
					return localVarReturnValue, localVarHttpResponse, newErr
				}
				newErr.model = v
				return localVarReturnValue, localVarHttpResponse, newErr
		}
		
		if localVarHttpResponse.StatusCode == 422 {
			var v ModelError
			err = a.client.decode(&v, localVarBody, localVarHttpResponse.Header.Get("Content-Type"));
				if err != nil {
					newErr.error = err.Error()
					return localVarReturnValue, localVarHttpResponse, newErr
				}
				newErr.model = v
				return localVarReturnValue, localVarHttpResponse, newErr
		}
		
		return localVarReturnValue, localVarHttpResponse, newErr
	}

	return localVarReturnValue, localVarHttpResponse, nil
}
