/*
 * Nodeum API
 *
 * # About  This document describes the Nodeum API version 2:  If you are looking for any information about the product itself, reach the product website https://www.nodeum.io. You can also contact us at this email address : info@nodeum.io  # Filter parameters When browsing a list of items, multiple filter parameters may be applied. Some operators can be added to the value as a prefix:  - `=` value is equal. Default operator, may be omitted  - `!=` value is different  - `>` greater than  - `>=` greater than or equal  - `<` lower than  - `>=` lower than or equal  - `><` included in list, items should be separated by `|`  - `!><` not included in list, items should be separated by `|`  - `~` pattern matching, may include `%` (any characters) and `_` (one character)  - `!~` pattern not matching, may include `%` (any characters) and `_` (one character)  
 *
 * API version: 2.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package nodeum

import (
	"bytes"
	"encoding/json"
)

// TapeDriveDeviceCollection struct for TapeDriveDeviceCollection
type TapeDriveDeviceCollection struct {
	TapeDrives *[]TapeDriveDevice `json:"tape_drives,omitempty"`
}

// GetTapeDrives returns the TapeDrives field value if set, zero value otherwise.
func (o *TapeDriveDeviceCollection) GetTapeDrives() []TapeDriveDevice {
	if o == nil || o.TapeDrives == nil {
		var ret []TapeDriveDevice
		return ret
	}
	return *o.TapeDrives
}

// GetTapeDrivesOk returns a tuple with the TapeDrives field value if set, zero value otherwise
// and a boolean to check if the value has been set.
func (o *TapeDriveDeviceCollection) GetTapeDrivesOk() ([]TapeDriveDevice, bool) {
	if o == nil || o.TapeDrives == nil {
		var ret []TapeDriveDevice
		return ret, false
	}
	return *o.TapeDrives, true
}

// HasTapeDrives returns a boolean if a field has been set.
func (o *TapeDriveDeviceCollection) HasTapeDrives() bool {
	if o != nil && o.TapeDrives != nil {
		return true
	}

	return false
}

// SetTapeDrives gets a reference to the given []TapeDriveDevice and assigns it to the TapeDrives field.
func (o *TapeDriveDeviceCollection) SetTapeDrives(v []TapeDriveDevice) {
	o.TapeDrives = &v
}

type NullableTapeDriveDeviceCollection struct {
	Value TapeDriveDeviceCollection
	ExplicitNull bool
}

func (v NullableTapeDriveDeviceCollection) MarshalJSON() ([]byte, error) {
    switch {
    case v.ExplicitNull:
        return []byte("null"), nil
    default:
		return json.Marshal(v.Value)
	}
}

func (v *NullableTapeDriveDeviceCollection) UnmarshalJSON(src []byte) error {
	if bytes.Equal(src, []byte("null")) {
		v.ExplicitNull = true
		return nil
	}

	return json.Unmarshal(src, &v.Value)
}
