#!/bin/bash

cd "`dirname \"$0\"`/.."

rm -rf api
rm -rf v2

docker run --rm \
    -v ${PWD}:/project \
    openapitools/openapi-generator-cli generate \
    -i https://api.swaggerhub.com/apis/Nodeum/nodeum/2.0.0 \
    -p sortParamsByRequiredFlag \
    -p packageName=nodeum \
    -p packageVersion=1.0.0 \
    -g go \
    -o /project/api

docker run --rm \
    -v ${PWD}:/project \
    openapitools/openapi-generator-cli generate \
    -i https://api.swaggerhub.com/apis/Nodeum/nodeum/2.1.0 \
    -p sortParamsByRequiredFlag \
    -p packageName=nodeum \
    -p packageVersion=2.0.0 \
    -g go \
    -o /project/v2
