/*
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package nodeum

type CloudPoolCollection struct {
	Count int32 `json:"count,omitempty"`
	CloudPools []CloudPool `json:"cloud_pools,omitempty"`
}
