/*
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package nodeum

type CloudBucket struct {
	Id int32 `json:"id,omitempty"`
	CloudConnectorId int32 `json:"cloud_connector_id,omitempty"`
	CloudPoolId int32 `json:"cloud_pool_id,omitempty"`
	Name string `json:"name,omitempty"`
	FilesCount int32 `json:"files_count,omitempty"`
	FilesSize int32 `json:"files_size,omitempty"`
	Location string `json:"location,omitempty"`
	Price string `json:"price,omitempty"`
}
